spring:
  jpa:
    hibernate:
      ddl-auto: update #update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false # waring : spring.jpa.open-in-view is enabled by default.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/pns_eis?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver #com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root

server:
  port: 8080
